### ISSUE TITLE
add a read more grid at the bottom of each single post

### ISSUE THREAD

**Issue by samccone** [mojotech/m-blog#29]
* design incoming via @ryancoughlin

**Comment by mordecai174** [comment]
this seems to be cleared up with disqus, unless we wanted to enhance or make any other improvements.

**Comment by mordecai174** [comment]
@kishfy ^

**Comment by kishfy** [comment]
I agree. This is done.

On Fri, Apr 3, 2015 at 11:01 AM, Matt Rossi <notifications@github.com>
wrote:

> @kishfy <https://github.com/kishfy> ^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojotech/m-blog/issues/29#issuecomment-89312857>.
>



-- 
Nick Kishfy
CEO, MojoTech
401.400.1971
http://mojotech.com
