### ISSUE TITLE
mobile scrolling feels very broken

### ISSUE THREAD

**Issue by samccone** [mojotech/m-blog#37]
Sometimes it works and other times it does not work.

**Comment by samccone** [comment]
after some thinking on this, pretty confident that the issue is from fastclick capturing the touch down events. 

we should just :x: it

**Comment by mordecai174** [comment]
seems to be fixed now from Jeff's latest PR. I think it was from snapdrawer.js

https://github.com/mojotech/m-blog/pull/46 removed it, she's running smooth now.
