### ISSUE TITLE
Add quick links to blog pages 1,2,3...25

### ISSUE THREAD

**Issue by courtsanks428** [mojotech/m-blog#39]
Allows users to jump to older pages without having to click "older posts" 24 times.

**Comment by samccone** [comment]
@courtsanks428 can you attach a screenshot of an example blog that does this well you think, so that whoever ends up picking this up will know what you have in mind.

Thanks and good idea :+1:

**Comment by Sheddybird** [comment]
:+1: 

Have you seen this control used in Ghost before @samccone ? 

It's a good idea, but let's be sure when prioritizing to challenge how much business value is created against how much effort will be required to deliver.

**Comment by courtsanks428** [comment]
For example: 
![screen shot 2015-03-04 at 4 12 42 pm](https://cloud.githubusercontent.com/assets/11299272/6493564/9496b100-c289-11e4-9ac6-e14b8d8098a7.png)

**Comment by samccone** [comment]
:+1: thanks :100:

**Comment by mordecai174** [comment]
we have infinite scrolling now, so this is no longer valid.

**Comment by courtsanks428** [comment]
Yay. Perfect.
