### ISSUE TITLE
Tag styles

### ISSUE THREAD

**Issue by mordecai174** [mojotech/m-blog#41]
Styles are needed now that tags have been added. Placement, styles and most importantly they should be navigable. They currently are just pieces of text.

**Comment by mrossimojo** [comment]
![image](https://cloud.githubusercontent.com/assets/4331569/6519696/03884860-c386-11e4-80e7-2c43b2eeeca1.jpg)

**Comment by courtsanks428** [comment]
Another post going up today and more in the queue. Can this get some love on Friday afternoon? #mojotime

**Comment by mordecai174** [comment]
we need this done first: https://github.com/mojotech/m-blog/issues/42
