### ISSUE TITLE
Add some space between other posts 

### ISSUE THREAD

**Issue by mordecai174** [mojotech/m-blog#74]
Need to add some space around these other posts at the bottom. Everything is jammed up on mobile. 
![image](https://cloud.githubusercontent.com/assets/4331569/7011086/2bca4f24-dc74-11e4-9716-5bb6e60588a2.jpg)

**Comment by lupinskij** [comment]
It's not possible to style any of the elements within the Disqus iframe using CSS.

**Comment by mordecai174** [comment]
wellp :wave:
