### ISSUE TITLE
Add Twitter Intents to blog posts to increase engagement. #552

### ISSUE THREAD

**Issue by samccone** [mojotech/m-blog#91]
via https://github.com/mojotech/m4/issues/552

**Comment by courtsanks428** [comment]
How do we feel about these callout boxes? Too disruptive or a good way to encourage engagement?
![screen shot 2015-05-29 at 12 08 59 pm](https://cloud.githubusercontent.com/assets/11299272/7886964/a0520732-05fb-11e5-90d6-a8d927c86b0a.png)

**Comment by kishfy** [comment]
I bet with the right design treatment they are good

**Comment by mordecai174** [comment]
yeah, we'll need to come up with some styles for this, but I do think it is a nice way to drive some engagement.
